csv_file_path: "data/sf-loan-performance-data-sample.csv"
column_mapping:
  11: "current_actual_upb"
  27: "property_type"
  39: "current_loan_delinquency_status"
  43: "zero_balance_code"
  23: "borrower_credit_score"
  19: "ltv_ratio"
  22: "debt_to_income"
  29: "occupancy_status"
  15: "loan_age"
  1: "loan_identifier"
  2: "loan_report_date"
loan_table_name: "client_loan_data"
sector_table_name: "sectors"
schema_file: "data/db_schema.sql"