training_csv_path: "data/2025Q3.csv"
simulation_csv_path: "data/2025Q4.csv"
column_mapping:
  11: "current_actual_upb"
  27: "property_type"
  39: "current_loan_delinquency_status"
  43: "zero_balance_code"
  23: "borrower_credit_score"
  19: "ltv_ratio"
  22: "debt_to_income"
  29: "occupancy_status"
  15: "loan_age"
  1: "loan_identifier"
  2: "loan_report_date"
simulation_table_name: "simulation_loan_data"
training_table_name: "training_loan_data"
sector_table_name: "sectors"
schema_file: "data/db_schema.sql"
model_save_dir: "models/"